version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/XEFAWztlVw/.circleci/config.yml
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run install
      - run: npm run lint
      - run: npm run test
